### ISSUE TITLE
No OTA download with Moto G5 plus

### ISSUE THREAD

**Issue by kerlerm** [erfanoabdi/Motorola-OTA-Link-Generator-Tool#3]
The tool does not seem to work with model "Moto G5 plus" (codename potter), which is on 8.1 since October 2018.

I'm on a custom ROM and tried to download the 8.1 OTA with values I got from fastboot:

sku: XT1685
ro.build.version.full[0]: Blur_Version.25.11.35.potter.reta
ro.build.version.full[1]: il.en.US
Blur_Version.25.11.35.potter.retail.en.US
ro.carrier: reteu 

Output: Something Looks Wrong ReCheck inputs Or No Update Available

**Comment by erfanoabdi** [comment]
https://motoota.lolinet.com/?model=Moto+G+%285%29+Plus&sv=Blur_Version.25.11.35.potter.retail.en.US&carrier=reteu&sn=

"ro.product.model=Moto G (5) Plus"
you had to use ro.product.model not sku ;)

**Comment by kerlerm** [comment]
Ups. I interpolated the naming scheme by looking at your examples... Sorry for the noise and thanks for the hint!

Cool tool :)
